// Built-in phrase categories for Antok Phrases.
// Each category: { id, name, language: 'tagalog'|'english', puzzles }
// Each puzzle: { prompt, answer, difficulty }
//
// The prompt is phonetic gibberish shown to everyone. It should be solved by
// reading it out loud, not by interpreting its written meaning. The answer is
// kept Host-only and must stay plain A-Z + spaces so letter tiles remain simple.

export const CATEGORIES = [
  {
    id: 'movie-lines-en',
    name: 'Movie Lines',
    language: 'english',
    puzzles: [
      { prompt: 'ILL BEE BACH', answer: 'ILL BE BACK', difficulty: 'easy' },
      { prompt: 'WHY SO CEREAL', answer: 'WHY SO SERIOUS', difficulty: 'easy' },
      { prompt: 'YOU TALL KING TO ME', answer: 'YOU TALKING TO ME', difficulty: 'easy' },
      { prompt: 'MAY THE FOURTHS BEE WITH YOU', answer: 'MAY THE FORCE BE WITH YOU', difficulty: 'easy' },
      { prompt: 'HOUSTON WE HAVE A PROB LAMB', answer: 'HOUSTON WE HAVE A PROBLEM', difficulty: 'medium' },
      { prompt: 'LIFE IS LIKE A BOX OF CHALK LETS', answer: 'LIFE IS LIKE A BOX OF CHOCOLATES', difficulty: 'medium' },
      { prompt: 'THERES NO PLAY SLICK HOME', answer: 'THERES NO PLACE LIKE HOME', difficulty: 'medium' },
      { prompt: 'I SEE DEAD PEE PULL', answer: 'I SEE DEAD PEOPLE', difficulty: 'medium' },
      { prompt: 'ELEMENT AIRY MY DEER WATT SUN', answer: 'ELEMENTARY MY DEAR WATSON', difficulty: 'hard' },
      { prompt: 'KEEP YOUR FRIENDS CLOSE AND YOUR ANEMIES CLOSER', answer: 'KEEP YOUR FRIENDS CLOSE AND YOUR ENEMIES CLOSER', difficulty: 'hard' },
      { prompt: 'HERE IS LOOKING ATCHEW KID', answer: 'HERES LOOKING AT YOU KID', difficulty: 'hard' },
      { prompt: 'TOO INFINITY AND BEE YAWNED', answer: 'TO INFINITY AND BEYOND', difficulty: 'hard' },
    ],
  },
  {
    id: 'sayings-en',
    name: 'Famous Sayings',
    language: 'english',
    puzzles: [
      { prompt: 'AWE LIVE VIEW', answer: 'I LOVE YOU', difficulty: 'easy' },
      { prompt: 'WONCE UPON A THYME', answer: 'ONCE UPON A TIME', difficulty: 'easy' },
      { prompt: 'BREAK A LAG', answer: 'BREAK A LEG', difficulty: 'easy' },
      { prompt: 'PIECE OFF CAKE', answer: 'PIECE OF CAKE', difficulty: 'easy' },
      { prompt: 'BITE THE BULL IT', answer: 'BITE THE BULLET', difficulty: 'medium' },
      { prompt: 'SPILL THE BEENZ', answer: 'SPILL THE BEANS', difficulty: 'medium' },
      { prompt: 'HIT THE SACKS', answer: 'HIT THE SACK', difficulty: 'medium' },
      { prompt: 'UNDER THE WHETHER', answer: 'UNDER THE WEATHER', difficulty: 'medium' },
      { prompt: 'TOO BEE OAR KNOT TOO BEE', answer: 'TO BE OR NOT TO BE', difficulty: 'hard' },
      { prompt: 'THE PEN IS MITE HEAR THAN THE SWORD', answer: 'THE PEN IS MIGHTIER THAN THE SWORD', difficulty: 'hard' },
      { prompt: 'ALL THAT GLITTERS IS KNOT GOLD', answer: 'ALL THAT GLITTERS IS NOT GOLD', difficulty: 'hard' },
      { prompt: 'FORTUNE FAVORS THE BOWLED', answer: 'FORTUNE FAVORS THE BOLD', difficulty: 'hard' },
    ],
  },
  {
    id: 'music-pop-en',
    name: 'Songs & Pop',
    language: 'english',
    puzzles: [
      { prompt: 'LIT IT GO', answer: 'LET IT GO', difficulty: 'easy' },
      { prompt: 'BEE OUR GUEST', answer: 'BE OUR GUEST', difficulty: 'easy' },
      { prompt: 'HELLO FROM THE OTTER SIDE', answer: 'HELLO FROM THE OTHER SIDE', difficulty: 'easy' },
      { prompt: 'SHAKE IT AWE F', answer: 'SHAKE IT OFF', difficulty: 'easy' },
      { prompt: 'DONT STOP BEE LEAFING', answer: 'DONT STOP BELIEVING', difficulty: 'medium' },
      { prompt: 'SWEET CAROL LINE', answer: 'SWEET CAROLINE', difficulty: 'medium' },
      { prompt: 'NO WOMAN NO CRYING', answer: 'NO WOMAN NO CRY', difficulty: 'medium' },
      { prompt: 'EYE OF THE TIE GIR', answer: 'EYE OF THE TIGER', difficulty: 'medium' },
      { prompt: 'WE WILL ROCK CHEW', answer: 'WE WILL ROCK YOU', difficulty: 'hard' },
      { prompt: 'I WANT IT THAT WEIGH', answer: 'I WANT IT THAT WAY', difficulty: 'hard' },
      { prompt: 'DANCING QUEUE IN', answer: 'DANCING QUEEN', difficulty: 'hard' },
      { prompt: 'HIT ME BABY WON MORE THYME', answer: 'HIT ME BABY ONE MORE TIME', difficulty: 'hard' },
    ],
  },
  {
    id: 'party-chaos-en',
    name: 'Party Chaos',
    language: 'english',
    puzzles: [
      { prompt: 'WE DYNAMIC CUP PULL', answer: 'WIN A MATCHING COUPLE', difficulty: 'easy' },
      { prompt: 'PASS THE MY CRO PHONE', answer: 'PASS THE MICROPHONE', difficulty: 'easy' },
      { prompt: 'TIME IS UP PENCILS DOWN', answer: 'TIMES UP PENCILS DOWN', difficulty: 'easy' },
      { prompt: 'READ IT OUT LAUD', answer: 'READ IT OUT LOUD', difficulty: 'easy' },
      { prompt: 'WHOSE TURN ISSET ANYWAY', answer: 'WHOSE TURN IS IT ANYWAY', difficulty: 'medium' },
      { prompt: 'SAY WHAT AGAN', answer: 'SAY WHAT AGAIN', difficulty: 'medium' },
      { prompt: 'THE ANSWER IS WRITE THERE', answer: 'THE ANSWER IS RIGHT THERE', difficulty: 'medium' },
      { prompt: 'THINK FAST DONT BLANK', answer: 'THINK FAST DONT BLINK', difficulty: 'medium' },
      { prompt: 'ABSOLUTE NON SENSE', answer: 'ABSOLUTE NONSENSE', difficulty: 'hard' },
      { prompt: 'CHAOS IS A LAD HER', answer: 'CHAOS IS A LADDER', difficulty: 'hard' },
      { prompt: 'LISTEN WITH YOUR EAR RINGS', answer: 'LISTEN WITH YOUR EARS', difficulty: 'hard' },
      { prompt: 'THE CLOCK IS TICK KING', answer: 'THE CLOCK IS TICKING', difficulty: 'hard' },
    ],
  },
  {
    id: 'pinoy-lines',
    name: 'Pinoy Lines',
    language: 'tagalog',
    puzzles: [
      { prompt: 'MA HALL KITA', answer: 'MAHAL KITA', difficulty: 'easy' },
      { prompt: 'WAH LANG FOUR EVER', answer: 'WALANG FOREVER', difficulty: 'easy' },
      { prompt: 'BA HAY COO BOW', answer: 'BAHAY KUBO', difficulty: 'easy' },
      { prompt: 'TUBBY TUBBY PO', answer: 'TABI TABI PO', difficulty: 'easy' },
      { prompt: 'WAH LANG HE MAH LAH', answer: 'WALANG HIMALA', difficulty: 'medium' },
      { prompt: 'HINDI KITA MA REACH', answer: 'HINDI KITA MAREACH', difficulty: 'medium' },
      { prompt: 'ANG BUH HAY I WEATHER WEATHER LANG', answer: 'ANG BUHAY AY WEATHER WEATHER LANG', difficulty: 'medium' },
      { prompt: 'BA KIT MA LUNG COT ANG BESHY KO', answer: 'BAKIT MALUNGKOT ANG BESHY KO', difficulty: 'medium' },
      { prompt: 'TIE YO NASA ANTI POLO', answer: 'TAYO NA SA ANTIPOLO', difficulty: 'hard' },
      { prompt: 'NA SUNK A MARUJA', answer: 'NASAAN KA MARUJA', difficulty: 'hard' },
      { prompt: 'A KNOCK', answer: 'ANAK', difficulty: 'hard' },
      { prompt: 'HE TOE ANG GUSTO KO', answer: 'ITO ANG GUSTO KO', difficulty: 'hard' },
    ],
  },
  {
    id: 'pinoy-party',
    name: 'Pinoy Party',
    language: 'tagalog',
    puzzles: [
      { prompt: 'PWEDE NA YARN', answer: 'PWEDE NA YAN', difficulty: 'easy' },
      { prompt: 'PAH KAIN NA', answer: 'KAIN NA', difficulty: 'easy' },
      { prompt: 'SAND DALLY LANG', answer: 'SANDALI LANG', difficulty: 'easy' },
      { prompt: 'ING GAT KA', answer: 'INGAT KA', difficulty: 'easy' },
      { prompt: 'ANO BA YARN', answer: 'ANO BA YAN', difficulty: 'medium' },
      { prompt: 'GAME NA BAAH', answer: 'GAME NA BA', difficulty: 'medium' },
      { prompt: 'KUHA MO BA TOH', answer: 'KUHA MO BA TO', difficulty: 'medium' },
      { prompt: 'LAG GOT KA KAY HOST', answer: 'LAGOT KA KAY HOST', difficulty: 'medium' },
      { prompt: 'HULAAN MO ANG SA GOT', answer: 'HULAAN MO ANG SAGOT', difficulty: 'hard' },
      { prompt: 'BASA HIN MO NANG MALAKAS', answer: 'BASAHIN MO NANG MALAKAS', difficulty: 'hard' },
      { prompt: 'PA RAW KANG AN TALK NA AN TALK', answer: 'PARA KANG ANTOK NA ANTOK', difficulty: 'hard' },
      { prompt: 'SEE GAW MO COOK ALAM MO', answer: 'SIGAW MO KUNG ALAM MO', difficulty: 'hard' },
    ],
  },
];
