// Built-in phrase categories for Antok Phrases.
// Each category: { id, name, language: 'tagalog'|'english', puzzles }
// Each puzzle: { prompt, answer, difficulty }
//
// The prompt is phonetic gibberish shown to everyone. It should be solved by
// reading it out loud, not by interpreting its written meaning. The answer is
// kept Host-only and must stay plain A-Z + spaces so letter tiles remain simple.

export const CATEGORIES = [
  {
    id: 'movie-lines-en',
    name: 'Movie Lines',
    language: 'english',
    puzzles: [
      { prompt: 'EEL BEE BAK', answer: 'ILL BE BACK', difficulty: 'easy' },
      { prompt: 'Y SEW SEER E US', answer: 'WHY SO SERIOUS', difficulty: 'easy' },
      { prompt: 'YEW TALL KING TWO MEE', answer: 'YOU TALKING TO ME', difficulty: 'easy' },
      { prompt: 'MAI DUH FOURSS BEE WHIFF YEW', answer: 'MAY THE FORCE BE WITH YOU', difficulty: 'easy' },
      { prompt: 'HUE STUN WII HAV UH PROB LEM', answer: 'HOUSTON WE HAVE A PROBLEM', difficulty: 'medium' },
      { prompt: 'LIE FIZZ LYE KUH BOKS UV CHALK LETS', answer: 'LIFE IS LIKE A BOX OF CHOCOLATES', difficulty: 'medium' },
      { prompt: 'DAIRS KNOW PLAY SLICK HONE', answer: 'THERES NO PLACE LIKE HOME', difficulty: 'medium' },
      { prompt: 'EYE SEA DED PEE PULL', answer: 'I SEE DEAD PEOPLE', difficulty: 'medium' },
      { prompt: 'ELEMENT AIRY MAI DEER WATT SUN', answer: 'ELEMENTARY MY DEAR WATSON', difficulty: 'hard' },
      { prompt: 'KEAP YER FRENS CLOZE AN YER EN UH MEES CLOZE ER', answer: 'KEEP YOUR FRIENDS CLOSE AND YOUR ENEMIES CLOSER', difficulty: 'hard' },
      { prompt: 'HAIR IZ LOOK IN ATCHEW KIDD', answer: 'HERES LOOKING AT YOU KID', difficulty: 'hard' },
      { prompt: 'TWO IN FIN UH TEE AN BEE YAWNED', answer: 'TO INFINITY AND BEYOND', difficulty: 'hard' },
    ],
  },
  {
    id: 'sayings-en',
    name: 'Famous Sayings',
    language: 'english',
    puzzles: [
      { prompt: 'AWE LIVE VIEW', answer: 'I LOVE YOU', difficulty: 'easy' },
      { prompt: 'WON SUP PON UH THYME', answer: 'ONCE UPON A TIME', difficulty: 'easy' },
      { prompt: 'BRAKE UH LAG', answer: 'BREAK A LEG', difficulty: 'easy' },
      { prompt: 'PEAS OV KAYK', answer: 'PIECE OF CAKE', difficulty: 'easy' },
      { prompt: 'BYTE DUH BULL IT', answer: 'BITE THE BULLET', difficulty: 'medium' },
      { prompt: 'SPYLL DUH BEENZ', answer: 'SPILL THE BEANS', difficulty: 'medium' },
      { prompt: 'HYT DUH SAKS', answer: 'HIT THE SACK', difficulty: 'medium' },
      { prompt: 'UN DUR DUH WHETHER', answer: 'UNDER THE WEATHER', difficulty: 'medium' },
      { prompt: 'TOO BEE OAR KNOT TOO BEE', answer: 'TO BE OR NOT TO BE', difficulty: 'hard' },
      { prompt: 'DUH PENN IZZ MITE HEAR DEN DUH SORD', answer: 'THE PEN IS MIGHTIER THAN THE SWORD', difficulty: 'hard' },
      { prompt: 'OLL DAT GLIT ERRS IZZ KNOT GOALD', answer: 'ALL THAT GLITTERS IS NOT GOLD', difficulty: 'hard' },
      { prompt: 'FOUR CHIN FAY VERS DUH BOWLED', answer: 'FORTUNE FAVORS THE BOLD', difficulty: 'hard' },
    ],
  },
  {
    id: 'music-pop-en',
    name: 'Songs & Pop',
    language: 'english',
    puzzles: [
      { prompt: 'LIT EHT GOH', answer: 'LET IT GO', difficulty: 'easy' },
      { prompt: 'BEE ARE GHEST', answer: 'BE OUR GUEST', difficulty: 'easy' },
      { prompt: 'HEH LOW FRUM DUH OTTER SYDE', answer: 'HELLO FROM THE OTHER SIDE', difficulty: 'easy' },
      { prompt: 'SHAY KET AWE F', answer: 'SHAKE IT OFF', difficulty: 'easy' },
      { prompt: 'DUN STAHPP BEE LEAFING', answer: 'DONT STOP BELIEVING', difficulty: 'medium' },
      { prompt: 'SWEE T CAROL LINE', answer: 'SWEET CAROLINE', difficulty: 'medium' },
      { prompt: 'KNOW WUH MEN KNOW CRYING', answer: 'NO WOMAN NO CRY', difficulty: 'medium' },
      { prompt: 'AYE UV DUH TIE GIR', answer: 'EYE OF THE TIGER', difficulty: 'medium' },
      { prompt: 'WII WIL ROK CHEW', answer: 'WE WILL ROCK YOU', difficulty: 'hard' },
      { prompt: 'EYE WAHNT EHT DAT WEIGH', answer: 'I WANT IT THAT WAY', difficulty: 'hard' },
      { prompt: 'DAN SING QUEUE IN', answer: 'DANCING QUEEN', difficulty: 'hard' },
      { prompt: 'HYT MEE BAY BEE WON MOR THYME', answer: 'HIT ME BABY ONE MORE TIME', difficulty: 'hard' },
    ],
  },
  {
    id: 'party-chaos-en',
    name: 'Party Chaos',
    language: 'english',
    puzzles: [
      { prompt: 'WE DYNAMIC CUP PULL', answer: 'WIN A MATCHING COUPLE', difficulty: 'easy' },
      { prompt: 'PAZ DUH MY CRO FONE', answer: 'PASS THE MICROPHONE', difficulty: 'easy' },
      { prompt: 'TYME IZ UPP PENCILZ DOWNE', answer: 'TIMES UP PENCILS DOWN', difficulty: 'easy' },
      { prompt: 'REED EHT OWT LAUD', answer: 'READ IT OUT LOUD', difficulty: 'easy' },
      { prompt: 'HOOZ TERN IZZET ANY WEIGH', answer: 'WHOSE TURN IS IT ANYWAY', difficulty: 'medium' },
      { prompt: 'SEH WUT AGAN', answer: 'SAY WHAT AGAIN', difficulty: 'medium' },
      { prompt: 'DUH ANSIR IZZ RITE DAIR', answer: 'THE ANSWER IS RIGHT THERE', difficulty: 'medium' },
      { prompt: 'THYNC FASST DUN BLANK', answer: 'THINK FAST DONT BLINK', difficulty: 'medium' },
      { prompt: 'AB SO LOOT NON SENSE', answer: 'ABSOLUTE NONSENSE', difficulty: 'hard' },
      { prompt: 'KAY OSS IZZ UH LAD HER', answer: 'CHAOS IS A LADDER', difficulty: 'hard' },
      { prompt: 'LISSEN WHIFF YER EAR RINGS', answer: 'LISTEN WITH YOUR EARS', difficulty: 'hard' },
      { prompt: 'DUH KLOK IZZ TICK KING', answer: 'THE CLOCK IS TICKING', difficulty: 'hard' },
    ],
  },
  {
    id: 'pinoy-lines',
    name: 'Pinoy Lines',
    language: 'tagalog',
    puzzles: [
      { prompt: 'MA HALL KEY TAH', answer: 'MAHAL KITA', difficulty: 'easy' },
      { prompt: 'WAH LANG FOUR EVER', answer: 'WALANG FOREVER', difficulty: 'easy' },
      { prompt: 'BA HAY COO BOW', answer: 'BAHAY KUBO', difficulty: 'easy' },
      { prompt: 'TUBBY TUBBY POH', answer: 'TABI TABI PO', difficulty: 'easy' },
      { prompt: 'WAH LANG HE MAH LAH', answer: 'WALANG HIMALA', difficulty: 'medium' },
      { prompt: 'HIN DEE KEY TAH MA REACH', answer: 'HINDI KITA MAREACH', difficulty: 'medium' },
      { prompt: 'UNG BUH HAY EYE WED ER WED ER LAHNG', answer: 'ANG BUHAY AY WEATHER WEATHER LANG', difficulty: 'medium' },
      { prompt: 'BAH KIT MAH LOONG COT UNG BESH EE KOH', answer: 'BAKIT MALUNGKOT ANG BESHY KO', difficulty: 'medium' },
      { prompt: 'TIE YO NASA ANTI POLO', answer: 'TAYO NA SA ANTIPOLO', difficulty: 'hard' },
      { prompt: 'NA SUNK AH MA ROO JA', answer: 'NASAAN KA MARUJA', difficulty: 'hard' },
      { prompt: 'A KNOCK', answer: 'ANAK', difficulty: 'hard' },
      { prompt: 'HE TOE UNG GOOS TOH KOH', answer: 'ITO ANG GUSTO KO', difficulty: 'hard' },
    ],
  },
  {
    id: 'pinoy-party',
    name: 'Pinoy Party',
    language: 'tagalog',
    puzzles: [
      { prompt: 'PWEH DEH NAH YARN', answer: 'PWEDE NA YAN', difficulty: 'easy' },
      { prompt: 'PAH KYN NAH', answer: 'KAIN NA', difficulty: 'easy' },
      { prompt: 'SAN DALLY LAHNG', answer: 'SANDALI LANG', difficulty: 'easy' },
      { prompt: 'EENG GAT KAH', answer: 'INGAT KA', difficulty: 'easy' },
      { prompt: 'AH NOH BAH YARN', answer: 'ANO BA YAN', difficulty: 'medium' },
      { prompt: 'GAYM NAH BAAH', answer: 'GAME NA BA', difficulty: 'medium' },
      { prompt: 'KOO HA MOH BAH TOH', answer: 'KUHA MO BA TO', difficulty: 'medium' },
      { prompt: 'LAH GOT KAH KAI HAUST', answer: 'LAGOT KA KAY HOST', difficulty: 'medium' },
      { prompt: 'HOO LAAN MOH UNG SA GOT', answer: 'HULAAN MO ANG SAGOT', difficulty: 'hard' },
      { prompt: 'BA SAH HIN MOH NUNG MAH LAH KAS', answer: 'BASAHIN MO NANG MALAKAS', difficulty: 'hard' },
      { prompt: 'PA RAW KAHNG AN TALK NAH AN TALK', answer: 'PARA KANG ANTOK NA ANTOK', difficulty: 'hard' },
      { prompt: 'SEE GAW MOH KOONG AH LAM MOH', answer: 'SIGAW MO KUNG ALAM MO', difficulty: 'hard' },
    ],
  },
];
